### ISSUE TITLE
Changing brightness doesn't work (permission denied)

### ISSUE THREAD

**Issue by vvirag** [kmARC/dotfiles#2]
The key bindings are set correctly under `sxhkdrc`, and by pressing `XF86MonBrightness{Up,Down}` the
`~/bin/backlight.sh {up, down}` script is called. However, it ends up exiting with permission denied exception.

I guess there should be a better solution (elevating permission at call?) than changing access rights of `/sys/class/backlight/intel_backlight` (the file that the `backlight.sh` script boils down to).

Any suggestion?

**Comment by kmARC** [comment]
Fixed in c28ff1b

https://github.com/kmARC/dotfiles/blob/master/etc/rc.local#L2
